sudo: required
dist: trusty
language: node_js

cache:
  directories:
    - node_modules
    - ~/.selenium-assistant
os:
  - linux
  - osx

# This is needed to make NVM happy on OS X https://github.com/travis-ci/travis-ci/issues/6476
osx_image: xcode7.3

node_js:
  - '6'
  - '7'

install:
  - npm install

# Read more here: https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start || echo \"Unable to start virtual display.\""
  - sleep 3 # give xvfb some time to start

script:
  - npm run test
