os: linux
dist: xenial
language: node_js

node_js:
  - '12'
  - '8'

addons:
  apt:
    update: true
    sources:
      - google-chrome
    packages:
      - dpkg

services:
  - xvfb

install:
  - npm install

script:
  - npm test
